---
- name: Download repo key
  ansible.builtin.shell:
    cmd: "curl -sSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x52B59B1571A79DBC054901C0F6BC817356A3D45E' | gpg --dearmor --output {{ golang_keyring }}"
    creates: "{{ golang_keyring }}"
  tags:
    - golang

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ golang_keyring }}] https://ppa.launchpadcontent.net/longsleep/golang-backports/ubuntu {{ ansible_distribution_release }} main"
    filename: golang
    update_cache: True
    state: present
  tags:
    - golang

- name: Install required packages
  loop: "{{ golang_versions }}"
  ansible.builtin.package:
    name: "golang-{{ item }}"
    state: present
  tags:
    - golang

- name: Drop outdated packages
  loop: "{{ golang_purge }}"
  ansible.builtin.package:
    name: "golang-{{ item }}"
    state: absent
  tags:
    - golang

- name: Symlink golang executable
  when: golang_symlink | default(False)
  loop:
    - go
    - gofmt
  ansible.builtin.file:
    src: "/usr/lib/go-{{ golang_symlink }}/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    state: link
  tags:
    - golang

...
